### configuration.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# see https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 106
  unit_system: imperial
  time_zone: America/New_York
  name: Home
  customize: !import overrides/customize.yaml
  customize_glob: !import overrides/customize_glob.yaml
  packages: !include_dir_named packages/

# Text to Speech default
tts:
  - platform: google_translate

http: !include http.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
